# Results

### Data Format
Shape: # of parameters $\times$ # of settings $\times$ # of metrics

Imports:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import itertools

Set path:

In [2]:
#path = 'C:/Users/Johan/Dropbox (Institut für Statistik)/Structural Breaks + DL/Simulation/Results/Simulation results/'
path = 'C:/Users/Meier/Dropbox (Institut für Statistik)/Structural Breaks + DL/Simulation/Results/Simulation results/'

Set metric:

In [3]:
metric = 0 # MSE: 0, MAE: 1, MAPE: 2, R^2: 3

Get names of simulation settings:

In [6]:
%run "Helper_functions.ipynb" # notebook containing helper functions

In [7]:
tau = np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7])  # break locations
fac_beta = np.array([0.5,1,2])                 # break size factor

In [8]:
str_sims = get_str_sims(tau, fac_beta) # get names of simulation settings
print(str_sims)

['Ref', 'Tau0.1Ref', 'Tau0.1Beta0.5', 'Tau0.1Beta1.0', 'Tau0.1Beta2.0', 'Tau0.2Ref', 'Tau0.2Beta0.5', 'Tau0.2Beta1.0', 'Tau0.2Beta2.0', 'Tau0.3Ref', 'Tau0.3Beta0.5', 'Tau0.3Beta1.0', 'Tau0.3Beta2.0', 'Tau0.4Ref', 'Tau0.4Beta0.5', 'Tau0.4Beta1.0', 'Tau0.4Beta2.0', 'Tau0.5Ref', 'Tau0.5Beta0.5', 'Tau0.5Beta1.0', 'Tau0.5Beta2.0', 'Tau0.6Ref', 'Tau0.6Beta0.5', 'Tau0.6Beta1.0', 'Tau0.6Beta2.0', 'Tau0.7Ref', 'Tau0.7Beta0.5', 'Tau0.7Beta1.0', 'Tau0.7Beta2.0']

# Setting 1

Reference table without breaks:

In [70]:
columns = ['AR', 'RNN', 'LSTM', 'GRU']
ind1 = ['$\\phi$']
ind2 = ['0.1','0.5','0.9','0.95','0.99']
index = pd.MultiIndex.from_tuples(list(itertools.product(ind1,ind2)))
df_setting1 = pd.DataFrame(columns = columns, index = index)

In [71]:
#str_model = ['AR', 'RNN', 'LSTM', 'GRU']
str_model = ['RNN', 'LSTM']
for i in str_model:
    with np.load(path+setting+'_'+i+'_results.npz') as data:
        df_setting1.loc[:,i] = data['mean'][:,0,metric] # mean value of metric for Ref

In [72]:
df_setting1

              AR       RNN      LSTM  GRU
$\phi$ 0.1   NaN  1.001181  1.001674  NaN
       0.5   NaN  0.994050  0.993519  NaN
       0.9   NaN  1.009099  1.007598  NaN
       0.95  NaN  0.993293  0.995443  NaN
       0.99  NaN  0.991767  0.986122  NaN

In [73]:
print(df_setting1.to_latex(float_format="%.4f", escape=False))

\begin{tabular}{lllrrl}
\toprule
       &      &   AR &    RNN &   LSTM &  GRU \\
\midrule
$\phi$ & 0.1 &  NaN & 1.0012 & 1.0017 &  NaN \\
       & 0.5 &  NaN & 0.9941 & 0.9935 &  NaN \\
       & 0.9 &  NaN & 1.0091 & 1.0076 &  NaN \\
       & 0.95 &  NaN & 0.9933 & 0.9954 &  NaN \\
       & 0.99 &  NaN & 0.9918 & 0.9861 &  NaN \\
\bottomrule
\end{tabular}

Table with breaks:

In [74]:
col1 = ['AR','RNN','LSTM','GRU']
col2 = ['$\\phi$']
col3 = ['0.1','0.5','0.9','0.95','0.99']
columns = pd.MultiIndex.from_tuples(list(itertools.product(col1, col2, col3)))
ind1 = ['$\text{sd}(\epsilon_t)/2$','$\text{sd}(\epsilon_t)$','$2\cdot\text{sd}(\epsilon_t)$']
ind2 = ['0.1','0.2','0.3','0.4','0.5','0.6','0.7']
#ind2 = ['0.1','0.3','0.5','0.7']
index = pd.MultiIndex.from_tuples(list(itertools.product(ind1, ind2)))
df_setting1_breaks = pd.DataFrame(columns = columns, index = index)
df_setting1_breaks.index.names = ['$\\beta$','$\\tau_0^*$']
df_setting1_breaks = df_setting1_breaks.T

In [75]:
#str_model = ['AR', 'RNN', 'LSTM', 'GRU']
str_model = ['RNN', 'LSTM']
for i in str_model:
    with np.load(path+setting+'_'+i+'_results.npz') as data:
        settings_ind = 2
        for j in ind2:
            df_setting1_breaks.loc[(i,col2),(ind1[0],j)] = np.round(data['mean'][:,settings_ind,metric],4) # mean value of metric for Tau0.1Beta0.5
            df_setting1_breaks.loc[(i,col2),(ind1[1],j)] = np.round(data['mean'][:,settings_ind+1,metric],4) # mean value of metric for Tau0.1Beta1.0
            df_setting1_breaks.loc[(i,col2),(ind1[2],j)] = np.round(data['mean'][:,settings_ind+2,metric],4) # mean value of metric for Tau0.1Beta2.0
            settings_ind += 4

In [103]:
df_setting1_breaks = df_setting1_breaks.drop(['0.2','0.4','0.6'],axis=1,level=1)

In [108]:
df_setting1_breaks

$\beta$          $\text{sd}(\epsilon_t)/2$                          \
$\tau_0^*$                             0.1     0.3     0.5     0.7
AR   $\phi$ 0.1                        NaN     NaN     NaN     NaN
            0.5                        NaN     NaN     NaN     NaN
            0.9                        NaN     NaN     NaN     NaN
            0.95                       NaN     NaN     NaN     NaN
            0.99                       NaN     NaN     NaN     NaN
RNN  $\phi$ 0.1                     1.0012  1.0008  1.0008  1.0049
            0.5                     0.9938   0.993  0.9938  1.0109
            0.9                     1.0088  1.0087  1.0088    1.01
            0.95                    0.9935  0.9933  0.9932   0.994
            0.99                    0.9916  0.9911  0.9908  0.9909
LSTM $\phi$ 0.1                     1.0013  1.0009  1.0014  1.0021
            0.5                     0.9929  0.9926  0.9921  1.0144
            0.9                     1.0074  1.0075  1.0082  1.0093
            0.95                    0.9952  0.9951  0.9957  0.9976
            0.99                    0.9865  0.9902  0.9925  0.9989
GRU  $\phi$ 0.1                        NaN     NaN     NaN     NaN
            0.5                        NaN     NaN     NaN     NaN
            0.9                        NaN     NaN     NaN     NaN
            0.95                       NaN     NaN     NaN     NaN
            0.99                       NaN     NaN     NaN     NaN

$\beta$          $\text{sd}(\epsilon_t)$                          \
$\tau_0^*$                           0.1     0.3     0.5     0.7
AR   $\phi$ 0.1                      NaN     NaN     NaN     NaN
            0.5                      NaN     NaN     NaN     NaN
            0.9                      NaN     NaN     NaN     NaN
            0.95                     NaN     NaN     NaN     NaN
            0.99                     NaN     NaN     NaN     NaN
RNN  $\phi$ 0.1                   1.0011  1.0015  1.0041  1.0172
            0.5                   0.9929  0.9936  0.9925    1.04
            0.9                   1.0084  1.0081  1.0086  1.0112
            0.95                  0.9938  0.9931   0.993  0.9946
            0.99                  0.9912  0.9906  0.9903   0.991
LSTM $\phi$ 0.1                   1.0011   1.002  1.0028   1.005
            0.5                   0.9923   0.992  0.9935  1.0508
            0.9                    1.007  1.0069  1.0081  1.0126
            0.95                  0.9952   0.995  0.9963  1.0007
            0.99                  0.9874  0.9929  0.9988  1.0243
GRU  $\phi$ 0.1                      NaN     NaN     NaN     NaN
            0.5                      NaN     NaN     NaN     NaN
            0.9                      NaN     NaN     NaN     NaN
            0.95                     NaN     NaN     NaN     NaN
            0.99                     NaN     NaN     NaN     NaN

$\beta$          $2\cdot\text{sd}(\epsilon_t)$
$\tau_0^*$                                 0.1     0.3     0.5     0.7
AR   $\phi$ 0.1                            NaN     NaN     NaN     NaN
            0.5                            NaN     NaN     NaN     NaN
            0.9                            NaN     NaN     NaN     NaN
            0.95                           NaN     NaN     NaN     NaN
            0.99                           NaN     NaN     NaN     NaN
RNN  $\phi$ 0.1                         1.0009  1.0052   1.016   1.016
            0.5                         0.9938  0.9928  1.0084  1.0822
            0.9                         1.0079  1.0077  1.0078  1.0147
            0.95                        0.9935  0.9939   0.993  0.9957
            0.99                        0.9908  0.9899    0.99  0.9911
LSTM $\phi$ 0.1                         1.0011  1.0034  1.0056  1.0076
            0.5                         0.9924  0.9967  1.0135  1.0659
            0.9                         1.0065  1.0065  1.0064  1.0192
            0.95                         0.995  0.9954  0.9956  1.0002
            0.99                        0.9879  0.9954  1.0042  1.0775
GRU  $\phi$ 0.1                            NaN     NaN     NaN     NaN
            0.5                            NaN     NaN     NaN     NaN
            0.9                            NaN     NaN     NaN     NaN
            0.95                           NaN     NaN     NaN     NaN
            0.99                           NaN     NaN     NaN     NaN

In [109]:
print(df_setting1_breaks.to_latex(escape=False))

\begin{tabular}{lllllllllllllll}
\toprule
    &        & $\beta$ & \multicolumn{4}{l}{$\text{sd}(\epsilon_t)/2$} & \multicolumn{4}{l}{$\text{sd}(\epsilon_t)$} & \multicolumn{4}{l}{$2\cdot\text{sd}(\epsilon_t)$} \\
    &        & $\tau_0^*$ &                       0.1 &     0.3 &     0.5 &     0.7 &                     0.1 &     0.3 &     0.5 &     0.7 &                           0.1 &     0.3 &     0.5 &     0.7 \\
\midrule
AR & $\phi$ & 0.1 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.5 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.9 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.95 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.99 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
RNN & $\phi$ & 0.1 &                    1.0012 &  1.0008 &  1.0008 &  1.0049 &                  1.0011 &  1.0015 &  1.0041 &  1.0172 &                        1.0009 &  1.0052 &   1.016 &   1.016 \\
    &        & 0.5 &                    0.9938 &   0.993 &  0.9938 &  1.0109 &                  0.9929 &  0.9936 &  0.9925 &    1.04 &                        0.9938 &  0.9928 &  1.0084 &  1.0822 \\
    &        & 0.9 &                    1.0088 &  1.0087 &  1.0088 &    1.01 &                  1.0084 &  1.0081 &  1.0086 &  1.0112 &                        1.0079 &  1.0077 &  1.0078 &  1.0147 \\
    &        & 0.95 &                    0.9935 &  0.9933 &  0.9932 &   0.994 &                  0.9938 &  0.9931 &   0.993 &  0.9946 &                        0.9935 &  0.9939 &   0.993 &  0.9957 \\
    &        & 0.99 &                    0.9916 &  0.9911 &  0.9908 &  0.9909 &                  0.9912 &  0.9906 &  0.9903 &   0.991 &                        0.9908 &  0.9899 &    0.99 &  0.9911 \\
LSTM & $\phi$ & 0.1 &                    1.0013 &  1.0009 &  1.0014 &  1.0021 &                  1.0011 &   1.002 &  1.0028 &   1.005 &                        1.0011 &  1.0034 &  1.0056 &  1.0076 \\
    &        & 0.5 &                    0.9929 &  0.9926 &  0.9921 &  1.0144 &                  0.9923 &   0.992 &  0.9935 &  1.0508 &                        0.9924 &  0.9967 &  1.0135 &  1.0659 \\
    &        & 0.9 &                    1.0074 &  1.0075 &  1.0082 &  1.0093 &                   1.007 &  1.0069 &  1.0081 &  1.0126 &                        1.0065 &  1.0065 &  1.0064 &  1.0192 \\
    &        & 0.95 &                    0.9952 &  0.9951 &  0.9957 &  0.9976 &                  0.9952 &   0.995 &  0.9963 &  1.0007 &                         0.995 &  0.9954 &  0.9956 &  1.0002 \\
    &        & 0.99 &                    0.9865 &  0.9902 &  0.9925 &  0.9989 &                  0.9874 &  0.9929 &  0.9988 &  1.0243 &                        0.9879 &  0.9954 &  1.0042 &  1.0775 \\
GRU & $\phi$ & 0.1 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.5 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.9 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.95 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.99 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
\bottomrule
\end{tabular}

Table with post-break observations:

In [78]:
col1 = ['AR','RNN','LSTM','GRU']
col2 = ['$\\phi$']
col3 = ['0.1','0.5','0.9','0.95','0.99']
columns = pd.MultiIndex.from_tuples(list(itertools.product(col1, col2, col3)))
ind1 = ['$\\tau_0^*$']
ind2 = ['0.1','0.2','0.3','0.4','0.5','0.6','0.7']
#ind2 = ['0.1','0.3','0.5','0.7']
index = pd.MultiIndex.from_tuples(list(itertools.product(ind1, ind2)))
df_setting1_postbreak = pd.DataFrame(columns = columns, index = index)
df_setting1_postbreak = df_setting1_postbreak.T

In [79]:
#str_model = ['AR', 'RNN', 'LSTM', 'GRU']
str_model = ['RNN', 'LSTM']
for i in str_model:
    with np.load(path+setting+'_'+i+'_results.npz') as data:
        settings_ind = 1
        for j in ind2:
            df_setting1_postbreak.loc[(i,col2),(ind1,j)] = np.round(data['mean'][:,settings_ind,metric],4) # mean value of metric for Tau0.1Ref
            settings_ind += 4

In [100]:
df_setting1_postbreak = df_setting1_postbreak.drop(['0.2','0.4','0.6'],axis=1,level=1)

In [101]:
df_setting1_postbreak

                 $\tau_0^*$
                        0.1     0.3     0.5     0.7
AR   $\phi$ 0.1         NaN     NaN     NaN     NaN
            0.5         NaN     NaN     NaN     NaN
            0.9         NaN     NaN     NaN     NaN
            0.95        NaN     NaN     NaN     NaN
            0.99        NaN     NaN     NaN     NaN
RNN  $\phi$ 0.1      1.0013  1.0014  1.0011  1.0015
            0.5      0.9941  0.9941  0.9942  0.9948
            0.9      1.0092  1.0094  1.0086  1.0114
            0.95     0.9934  0.9933  0.9941  0.9963
            0.99     0.9917  0.9922  0.9939  1.0141
LSTM $\phi$ 0.1      1.0015  1.0017  1.0018  1.0023
            0.5      0.9935  0.9933  0.9935  0.9946
            0.9      1.0078  1.0074   1.007  1.0098
            0.95     0.9955  0.9952  0.9958  1.0028
            0.99     0.9871  0.9924   0.999  1.1236
GRU  $\phi$ 0.1         NaN     NaN     NaN     NaN
            0.5         NaN     NaN     NaN     NaN
            0.9         NaN     NaN     NaN     NaN
            0.95        NaN     NaN     NaN     NaN
            0.99        NaN     NaN     NaN     NaN

In [102]:
print(df_setting1_postbreak.to_latex(escape=False))

\begin{tabular}{lllllll}
\toprule
    &        &      & \multicolumn{4}{l}{$\tau_0^*$} \\
    &        &      &        0.1 &     0.3 &     0.5 &     0.7 \\
\midrule
AR & $\phi$ & 0.1 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.5 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.9 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.95 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.99 &        NaN &     NaN &     NaN &     NaN \\
RNN & $\phi$ & 0.1 &     1.0013 &  1.0014 &  1.0011 &  1.0015 \\
    &        & 0.5 &     0.9941 &  0.9941 &  0.9942 &  0.9948 \\
    &        & 0.9 &     1.0092 &  1.0094 &  1.0086 &  1.0114 \\
    &        & 0.95 &     0.9934 &  0.9933 &  0.9941 &  0.9963 \\
    &        & 0.99 &     0.9917 &  0.9922 &  0.9939 &  1.0141 \\
LSTM & $\phi$ & 0.1 &     1.0015 &  1.0017 &  1.0018 &  1.0023 \\
    &        & 0.5 &     0.9935 &  0.9933 &  0.9935 &  0.9946 \\
    &        & 0.9 &     1.0078 &  1.0074 &   1.007 &  1.0098 \\
    &        & 0.95 &     0.9955 &  0.9952 &  0.9958 &  1.0028 \\
    &        & 0.99 &     0.9871 &  0.9924 &   0.999 &  1.1236 \\
GRU & $\phi$ & 0.1 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.5 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.9 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.95 &        NaN &     NaN &     NaN &     NaN \\
    &        & 0.99 &        NaN &     NaN &     NaN &     NaN \\
\bottomrule
\end{tabular}

Table with combination forecasts:

In [82]:
col1 = ['RNN','LSTM','GRU']
col2 = ['$\\phi$']
col3 = ['0.1','0.5','0.9','0.95','0.99']
columns = pd.MultiIndex.from_tuples(list(itertools.product(col1, col2, col3)))
ind1 = ['$\text{sd}(\epsilon_t)/2$','$\text{sd}(\epsilon_t)$','$2\cdot\text{sd}(\epsilon_t)$']
ind2 = ['0.1','0.2','0.3','0.4','0.5','0.6','0.7']
#ind2 = ['0.1','0.3','0.5','0.7']
index = pd.MultiIndex.from_tuples(list(itertools.product(ind1, ind2)))
df_setting1_combi = pd.DataFrame(columns = columns, index = index)
df_setting1_combi.index.names = ['$\\beta$','$\\tau_0^*$']
df_setting1_combi = df_setting1_combi.T

In [83]:
#str_model = ['AR', 'RNN', 'LSTM', 'GRU']
str_model = ['RNN', 'LSTM']
for i in str_model:
    with np.load(path+setting+'_'+i+'_ave_results.npz') as data:
        settings_ind = 2
        for j in ind2:
            df_setting1_combi.loc[(i,col2),(ind1[0],j)] = np.round(data['mean'][:,settings_ind,metric],4) # mean value of metric for Tau0.1Beta0.5
            df_setting1_combi.loc[(i,col2),(ind1[1],j)] = np.round(data['mean'][:,settings_ind+1,metric],4) # mean value of metric for Tau0.1Beta1.0
            df_setting1_combi.loc[(i,col2),(ind1[2],j)] = np.round(data['mean'][:,settings_ind+2,metric],4) # mean value of metric for Tau0.1Beta2.0
            settings_ind += 4

In [97]:
df_setting1_combi = df_setting1_combi.drop(['0.2','0.4','0.6'],axis=1,level=1)

In [112]:
df_setting1_combi

$\beta$          $\text{sd}(\epsilon_t)/2$                          \
$\tau_0^*$                             0.1     0.3     0.5     0.7
RNN  $\phi$ 0.1                     1.0022  1.0018  1.0018  1.0163
            0.5                     0.9944  0.9936  0.9948  1.0131
            0.9                     1.0097  1.0095  1.0095  1.0108
            0.95                    0.9943   0.994  0.9937  0.9949
            0.99                    0.9956  0.9947  0.9939   0.995
LSTM $\phi$ 0.1                     1.0024  1.0021  1.0042   1.006
            0.5                     0.9935  0.9939  0.9929  1.0167
            0.9                     1.0081  1.0083  1.0092  1.0106
            0.95                    0.9968  0.9969  0.9978  0.9999
            0.99                    0.9948   1.002  1.0051  1.0138
GRU  $\phi$ 0.1                        NaN     NaN     NaN     NaN
            0.5                        NaN     NaN     NaN     NaN
            0.9                        NaN     NaN     NaN     NaN
            0.95                       NaN     NaN     NaN     NaN
            0.99                       NaN     NaN     NaN     NaN

$\beta$          $\text{sd}(\epsilon_t)$                          \
$\tau_0^*$                           0.1     0.3     0.5     0.7
RNN  $\phi$ 0.1                   1.0028  1.0046  1.0134  1.0426
            0.5                   0.9937  0.9951  0.9934  1.0508
            0.9                   1.0091  1.0088  1.0094  1.0123
            0.95                  0.9942  0.9937  0.9935  0.9959
            0.99                  0.9945  0.9929  0.9925  0.9959
LSTM $\phi$ 0.1                   1.0031  1.0051  1.0057  1.0101
            0.5                   0.9929  0.9923  0.9956  1.0538
            0.9                   1.0076   1.008  1.0096  1.0154
            0.95                  0.9969  0.9972  0.9987  1.0038
            0.99                  0.9962  1.0084  1.0175  1.0551
GRU  $\phi$ 0.1                      NaN     NaN     NaN     NaN
            0.5                      NaN     NaN     NaN     NaN
            0.9                      NaN     NaN     NaN     NaN
            0.95                     NaN     NaN     NaN     NaN
            0.99                     NaN     NaN     NaN     NaN

$\beta$          $2\cdot\text{sd}(\epsilon_t)$
$\tau_0^*$                                 0.1     0.3     0.5     0.7
RNN  $\phi$ 0.1                         1.0039  1.0121  1.0383  1.1274
            0.5                         0.9944  0.9944  1.0128  1.1044
            0.9                         1.0084  1.0083  1.0089  1.0171
            0.95                         0.994  0.9944  0.9936  0.9991
            0.99                        0.9932  0.9913  0.9917  0.9995
LSTM $\phi$ 0.1                         1.0032  1.0049  1.0097  1.0142
            0.5                          0.993  0.9995  1.0177  1.0521
            0.9                         1.0073  1.0075  1.0079   1.023
            0.95                         0.997  0.9975  0.9996  1.0049
            0.99                        0.9989  1.0149  1.0331  1.1328
GRU  $\phi$ 0.1                            NaN     NaN     NaN     NaN
            0.5                            NaN     NaN     NaN     NaN
            0.9                            NaN     NaN     NaN     NaN
            0.95                           NaN     NaN     NaN     NaN
            0.99                           NaN     NaN     NaN     NaN

In [113]:
print(df_setting1_combi.to_latex(escape=False))

\begin{tabular}{lllllllllllllll}
\toprule
    &        & $\beta$ & \multicolumn{4}{l}{$\text{sd}(\epsilon_t)/2$} & \multicolumn{4}{l}{$\text{sd}(\epsilon_t)$} & \multicolumn{4}{l}{$2\cdot\text{sd}(\epsilon_t)$} \\
    &        & $\tau_0^*$ &                       0.1 &     0.3 &     0.5 &     0.7 &                     0.1 &     0.3 &     0.5 &     0.7 &                           0.1 &     0.3 &     0.5 &     0.7 \\
\midrule
RNN & $\phi$ & 0.1 &                    1.0022 &  1.0018 &  1.0018 &  1.0163 &                  1.0028 &  1.0046 &  1.0134 &  1.0426 &                        1.0039 &  1.0121 &  1.0383 &  1.1274 \\
    &        & 0.5 &                    0.9944 &  0.9936 &  0.9948 &  1.0131 &                  0.9937 &  0.9951 &  0.9934 &  1.0508 &                        0.9944 &  0.9944 &  1.0128 &  1.1044 \\
    &        & 0.9 &                    1.0097 &  1.0095 &  1.0095 &  1.0108 &                  1.0091 &  1.0088 &  1.0094 &  1.0123 &                        1.0084 &  1.0083 &  1.0089 &  1.0171 \\
    &        & 0.95 &                    0.9943 &   0.994 &  0.9937 &  0.9949 &                  0.9942 &  0.9937 &  0.9935 &  0.9959 &                         0.994 &  0.9944 &  0.9936 &  0.9991 \\
    &        & 0.99 &                    0.9956 &  0.9947 &  0.9939 &   0.995 &                  0.9945 &  0.9929 &  0.9925 &  0.9959 &                        0.9932 &  0.9913 &  0.9917 &  0.9995 \\
LSTM & $\phi$ & 0.1 &                    1.0024 &  1.0021 &  1.0042 &   1.006 &                  1.0031 &  1.0051 &  1.0057 &  1.0101 &                        1.0032 &  1.0049 &  1.0097 &  1.0142 \\
    &        & 0.5 &                    0.9935 &  0.9939 &  0.9929 &  1.0167 &                  0.9929 &  0.9923 &  0.9956 &  1.0538 &                         0.993 &  0.9995 &  1.0177 &  1.0521 \\
    &        & 0.9 &                    1.0081 &  1.0083 &  1.0092 &  1.0106 &                  1.0076 &   1.008 &  1.0096 &  1.0154 &                        1.0073 &  1.0075 &  1.0079 &   1.023 \\
    &        & 0.95 &                    0.9968 &  0.9969 &  0.9978 &  0.9999 &                  0.9969 &  0.9972 &  0.9987 &  1.0038 &                         0.997 &  0.9975 &  0.9996 &  1.0049 \\
    &        & 0.99 &                    0.9948 &   1.002 &  1.0051 &  1.0138 &                  0.9962 &  1.0084 &  1.0175 &  1.0551 &                        0.9989 &  1.0149 &  1.0331 &  1.1328 \\
GRU & $\phi$ & 0.1 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.5 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.9 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.95 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.99 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
\bottomrule
\end{tabular}

Table with EWS loss:

In [86]:
alpha = 0.999
batch_size = 64

In [87]:
col1 = ['RNN','LSTM','GRU']
col2 = ['$\\phi$']
col3 = ['0.1','0.5','0.9','0.95','0.99']
columns = pd.MultiIndex.from_tuples(list(itertools.product(col1, col2, col3)))
ind1 = ['$\text{sd}(\epsilon_t)/2$','$\text{sd}(\epsilon_t)$','$2\cdot\text{sd}(\epsilon_t)$']
ind2 = ['0.1','0.2','0.3','0.4','0.5','0.6','0.7']
#ind2 = ['0.1','0.3','0.5','0.7']
index = pd.MultiIndex.from_tuples(list(itertools.product(ind1, ind2)))
df_setting1_EWS = pd.DataFrame(columns = columns, index = index)
df_setting1_EWS.index.names = ['$\\beta$','$\\tau_0^*$']
df_setting1_EWS = df_setting1_EWS.T

In [88]:
#str_model = ['AR', 'RNN', 'LSTM', 'GRU']
str_model = ['RNN', 'LSTM']
for i in str_model:
    with np.load(path+setting+'_'+i+'_EWSLoss_'+str(alpha)+'_'+str(batch_size)+'_results.npz') as data:
        settings_ind = 2
        for j in ind2:
            df_setting1_EWS.loc[(i,col2),(ind1[0],j)] = np.round(data['mean'][:,settings_ind,metric],4) # mean value of metric for Tau0.1Beta0.5
            df_setting1_EWS.loc[(i,col2),(ind1[1],j)] = np.round(data['mean'][:,settings_ind+1,metric],4) # mean value of metric for Tau0.1Beta1.0
            df_setting1_EWS.loc[(i,col2),(ind1[2],j)] = np.round(data['mean'][:,settings_ind+2,metric],4) # mean value of metric for Tau0.1Beta2.0
            settings_ind += 4

In [94]:
df_setting1_EWS = df_setting1_EWS.drop(['0.2','0.4','0.6'],axis=1,level=1)

In [95]:
df_setting1_EWS

$\beta$          $\text{sd}(\epsilon_t)/2$                          \
$\tau_0^*$                             0.1     0.3     0.5     0.7
RNN  $\phi$ 0.1                     1.0024  1.0022  1.0022  1.0076
            0.5                     0.9916  0.9915  0.9906  0.9988
            0.9                     1.0062  1.0061  1.0059  1.0063
            0.95                    0.9963  0.9962  0.9962  0.9963
            0.99                    0.9855  0.9854  0.9856  0.9855
LSTM $\phi$ 0.1                     1.0055  1.0056  1.0055  1.0064
            0.5                     0.9952  0.9946   0.994  1.0144
            0.9                     1.0077  1.0079  1.0087  1.0072
            0.95                    1.0022  1.0023  1.0028  1.0043
            0.99                    0.9928  0.9975  1.0007  1.0055
GRU  $\phi$ 0.1                        NaN     NaN     NaN     NaN
            0.5                        NaN     NaN     NaN     NaN
            0.9                        NaN     NaN     NaN     NaN
            0.95                       NaN     NaN     NaN     NaN
            0.99                       NaN     NaN     NaN     NaN

$\beta$          $\text{sd}(\epsilon_t)$                          \
$\tau_0^*$                           0.1     0.3     0.5     0.7
RNN  $\phi$ 0.1                   1.0024  1.0022  1.0032   1.015
            0.5                   0.9916  0.9902  0.9911  1.0414
            0.9                   1.0059  1.0054  1.0055  1.0043
            0.95                  0.9963  0.9962  0.9959  0.9974
            0.99                  0.9853  0.9851  0.9852  0.9847
LSTM $\phi$ 0.1                   1.0056  1.0054  1.0059  1.0091
            0.5                    0.995  0.9942   0.994  1.0397
            0.9                   1.0076  1.0078  1.0078  1.0056
            0.95                  1.0022  1.0023  1.0028  1.0068
            0.99                  0.9932  0.9996  1.0018  1.0235
GRU  $\phi$ 0.1                      NaN     NaN     NaN     NaN
            0.5                      NaN     NaN     NaN     NaN
            0.9                      NaN     NaN     NaN     NaN
            0.95                     NaN     NaN     NaN     NaN
            0.99                     NaN     NaN     NaN     NaN

$\beta$          $2\cdot\text{sd}(\epsilon_t)$
$\tau_0^*$                                 0.1     0.3     0.5     0.7
RNN  $\phi$ 0.1                         1.0024  1.0022  1.0091  1.0205
            0.5                         0.9911  0.9907  0.9914  1.0459
            0.9                         1.0049  1.0041  1.0034  1.0061
            0.95                        0.9964  0.9961   0.996  1.0001
            0.99                        0.9852  0.9847  0.9846  0.9853
LSTM $\phi$ 0.1                         1.0056  1.0052  1.0086  1.0098
            0.5                         0.9947  0.9941  1.0038  1.0683
            0.9                         1.0073  1.0073  1.0064  1.0057
            0.95                        1.0027  1.0029  1.0028  1.0053
            0.99                         0.994  1.0016  1.0019  1.0351
GRU  $\phi$ 0.1                            NaN     NaN     NaN     NaN
            0.5                            NaN     NaN     NaN     NaN
            0.9                            NaN     NaN     NaN     NaN
            0.95                           NaN     NaN     NaN     NaN
            0.99                           NaN     NaN     NaN     NaN

In [96]:
print(df_setting1_EWS.to_latex(escape=False))

\begin{tabular}{lllllllllllllll}
\toprule
    &        & $\beta$ & \multicolumn{4}{l}{$\text{sd}(\epsilon_t)/2$} & \multicolumn{4}{l}{$\text{sd}(\epsilon_t)$} & \multicolumn{4}{l}{$2\cdot\text{sd}(\epsilon_t)$} \\
    &        & $\tau_0^*$ &                       0.1 &     0.3 &     0.5 &     0.7 &                     0.1 &     0.3 &     0.5 &     0.7 &                           0.1 &     0.3 &     0.5 &     0.7 \\
\midrule
RNN & $\phi$ & 0.1 &                    1.0024 &  1.0022 &  1.0022 &  1.0076 &                  1.0024 &  1.0022 &  1.0032 &   1.015 &                        1.0024 &  1.0022 &  1.0091 &  1.0205 \\
    &        & 0.5 &                    0.9916 &  0.9915 &  0.9906 &  0.9988 &                  0.9916 &  0.9902 &  0.9911 &  1.0414 &                        0.9911 &  0.9907 &  0.9914 &  1.0459 \\
    &        & 0.9 &                    1.0062 &  1.0061 &  1.0059 &  1.0063 &                  1.0059 &  1.0054 &  1.0055 &  1.0043 &                        1.0049 &  1.0041 &  1.0034 &  1.0061 \\
    &        & 0.95 &                    0.9963 &  0.9962 &  0.9962 &  0.9963 &                  0.9963 &  0.9962 &  0.9959 &  0.9974 &                        0.9964 &  0.9961 &   0.996 &  1.0001 \\
    &        & 0.99 &                    0.9855 &  0.9854 &  0.9856 &  0.9855 &                  0.9853 &  0.9851 &  0.9852 &  0.9847 &                        0.9852 &  0.9847 &  0.9846 &  0.9853 \\
LSTM & $\phi$ & 0.1 &                    1.0055 &  1.0056 &  1.0055 &  1.0064 &                  1.0056 &  1.0054 &  1.0059 &  1.0091 &                        1.0056 &  1.0052 &  1.0086 &  1.0098 \\
    &        & 0.5 &                    0.9952 &  0.9946 &   0.994 &  1.0144 &                   0.995 &  0.9942 &   0.994 &  1.0397 &                        0.9947 &  0.9941 &  1.0038 &  1.0683 \\
    &        & 0.9 &                    1.0077 &  1.0079 &  1.0087 &  1.0072 &                  1.0076 &  1.0078 &  1.0078 &  1.0056 &                        1.0073 &  1.0073 &  1.0064 &  1.0057 \\
    &        & 0.95 &                    1.0022 &  1.0023 &  1.0028 &  1.0043 &                  1.0022 &  1.0023 &  1.0028 &  1.0068 &                        1.0027 &  1.0029 &  1.0028 &  1.0053 \\
    &        & 0.99 &                    0.9928 &  0.9975 &  1.0007 &  1.0055 &                  0.9932 &  0.9996 &  1.0018 &  1.0235 &                         0.994 &  1.0016 &  1.0019 &  1.0351 \\
GRU & $\phi$ & 0.1 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.5 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.9 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.95 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
    &        & 0.99 &                       NaN &     NaN &     NaN &     NaN &                     NaN &     NaN &     NaN &     NaN &                           NaN &     NaN &     NaN &     NaN \\
\bottomrule
\end{tabular}

# Setting 2

# Setting 3